contentColumnType: string
fieldGroup: b24c2ab9-7552-4b71-9389-854d642238a5
handle: articles
instructions: ''
name: Articles
searchable: false
settings:
  contentTable: '{{%matrixcontent_articles}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
