enableVersioning: true
handle: news
name: News
propagationMethod: all
siteSettings:
  e0ab0c41-0d9a-4f78-961a-cb1c3b3a7684:
    enabledByDefault: true
    hasUrls: true
    template: news/index
    uriFormat: news
type: single
